name: Update Google Scholar Citations Badge

permissions:
  contents: write   # 允许修改仓库内容

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install scholarly
        run: pip install scholarly

      - name: Run update_scholar.py
        env:
          GOOGLE_SCHOLAR_ID: e5ng8m0AAAAJ    # 你的 Google Scholar ID
        run: python update_scholar.py

      - name: Commit and push results
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add results/*
          git commit -m "Update Scholar Badge JSON" --allow-empty
          git push
